# initial_config
random_seed: 3
eval_best: False
eval_random: False
eval_episodes: 500
best_model: models/best_models/arch3
epochs: 100
iters: 2500  # minibatches per epoch
n_episodes: 5

Trainer:
  update_target_freq: 100
  batch_size: 64
  lr: .005  # --> .005 * 0.9**20 == .00060788
  lr_gamma: .9
  lr_step_size: 5 # how often (epochs) to decrease lr 
  gamma: .95
  eps_max: 1.0
  eps_min: 0.1
  eps_freq: 1000
  eps_decrement: .01