# initial_config
random_seed: 3
eval_best: True
eval_random: True
eval_episodes: 500
best_model: models/best_models/arch0
epochs: 25
iters: 10000
n_episodes: 5

Trainer:
  update_target_freq: 500
  batch_size: 64
  lr: .005
  gamma: .95
  eps_max: 1.0
  eps_min: 0.1
  eps_freq: 10000
  eps_decrement: .01