DNU

# version: 1
# disable_existing_loggers: False
# formatters:
#   simple:
#     format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
# handlers:
#   file:
#     class: logging.FileHandler
#     level: INFO
#     formatter: simple
#     stream:
#   console:
#     class: logging.StreamHandler
#     level: DEBUG
#     formatter: simple
#     stream: ext://sys.stdout

# loggers:
#   my_logger:
#     level: DEBUG
#     handlers: [console]
#     propagate: no
# root:
#   level: DEBUG
#   handlers: [console]


# version: 1
# formatters:
#   simple:
#     format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
# handlers:
#   console:
#     class: logging.StreamHandler
#     level: DEBUG
#     formatter: simple
#     stream: ext://sys.stdout
# loggers:
#   sampleLogger:
#     level: DEBUG
#     handlers: [console]
#     propagate: no
# root:
#   level: DEBUG
#   handlers: [console]
